import { describe, expect, it } from 'vitest';
import { ControlledAutoExecutor, type AutoExecutionCommand, type BrokerPort, type BrokerOrderCommand, type BrokerOrderResult } from '../../src/application/broker-auto-execution.js';

class StubBroker implements BrokerPort {
  public calls: BrokerOrderCommand[] = [];
  public constructor(private readonly result: BrokerOrderResult = { clientOrderId: 'unused', state: 'ACCEPTED', externalOrderId: 'ext-1' }) {}
  public async place(command: BrokerOrderCommand): Promise<BrokerOrderResult> { this.calls.push(command); return { ...this.result, clientOrderId: command.clientOrderId }; }
  public async query(clientOrderId: string): Promise<BrokerOrderResult> { return { clientOrderId, state: 'UNKNOWN', reason: 'not implemented' }; }
  public async cancel(clientOrderId: string): Promise<BrokerOrderResult> { return { clientOrderId, state: 'REJECTED', reason: 'not implemented' }; }
}
const policy = { enabled: true, allowedAccountIds: ['paper-001'], allowedSecurityIds: ['SSE:600000'], allowedStrategyVersions: ['strategy-v1'], maxBatchNotional: 2_000, maxOrderNotional: 1_500, sessionStartUtc: '01:30', sessionEndUtc: '07:00', killSwitchOpen: true } as const;
const command: AutoExecutionCommand = { rebalanceBatchId: 'batch-auto-1', accountId: 'paper-001', strategyVersion: 'strategy-v1', approvalId: 'approval-1', riskEvaluationId: 'risk-1', budgetReservationId: 'budget-1', validUntil: '2026-09-05T08:00:00Z', executionAsOf: '2026-09-05T02:00:00Z', approvalComplete: true, riskApproved: true, budgetReserved: true, priceWithinTolerance: true, legs: [{ legId: 'leg-1', securityId: 'SSE:600000', side: 'BUY', quantity: '100', referencePrice: '10' }] };

describe('ControlledAutoExecutor', () => {
  it('校验门禁后按批次提交白名单订单并幂等', async () => { const broker = new StubBroker(); const executor = new ControlledAutoExecutor(broker, policy); const result = await executor.submit(command); expect(result.state).toBe('ACCEPTED'); expect(broker.calls).toHaveLength(1); expect(await executor.submit(command)).toEqual(result); expect(broker.calls).toHaveLength(1); });
  it('拒绝非白名单账户、超额和Kill Switch关闭', async () => { const broker = new StubBroker(); const executor = new ControlledAutoExecutor(broker, policy); expect((await executor.submit({ ...command, accountId: 'real-001' })).reason).toBe('ACCOUNT_NOT_WHITELISTED'); expect((await executor.submit({ ...command, rebalanceBatchId: 'batch-2', legs: [{ ...command.legs[0]!, quantity: '200' }] })).reason).toBe('ORDER_NOTIONAL_LIMIT_EXCEEDED'); expect((await new ControlledAutoExecutor(broker, { ...policy, killSwitchOpen: false }).submit({ ...command, rebalanceBatchId: 'batch-3' })).reason).toBe('KILL_SWITCH_CLOSED'); expect(broker.calls).toHaveLength(0); });
  it('Broker返回UNKNOWN后不自动重试', async () => { const broker = new StubBroker({ clientOrderId: 'unused', state: 'UNKNOWN' }); const executor = new ControlledAutoExecutor(broker, policy); const first = await executor.submit(command); const second = await executor.submit(command); expect(first.state).toBe('UNKNOWN'); expect(first.reason).toBe('BROKER_RESPONSE_UNKNOWN_NO_RETRY'); expect(second).toEqual(first); expect(broker.calls).toHaveLength(1); });
  it('拒绝过期、时段外和未完成前置审批', async () => { const broker = new StubBroker(); const executor = new ControlledAutoExecutor(broker, policy); expect((await executor.submit({ ...command, rebalanceBatchId: 'batch-4', validUntil: '2026-09-05T01:00:00Z' })).reason).toBe('EXECUTION_APPROVAL_EXPIRED'); expect((await executor.submit({ ...command, rebalanceBatchId: 'batch-5', executionAsOf: '2026-09-05T00:00:00Z' })).reason).toBe('OUTSIDE_TRADING_SESSION'); expect((await executor.submit({ ...command, rebalanceBatchId: 'batch-6', approvalComplete: false })).reason).toBe('PREFLIGHT_APPROVAL_INCOMPLETE'); });
  it('Feature Flag关闭时优先拒绝，不能发送Broker请求', async () => { const broker = new StubBroker(); const result = await new ControlledAutoExecutor(broker, { ...policy, enabled: false }).submit(command); expect(result.reason).toBe('AUTO_EXECUTION_DISABLED'); expect(broker.calls).toHaveLength(0); });
});
