import { Injectable } from '@nestjs/common';
import { ApprovalRecord, CreateProposalCommand, ProposalAggregate, RiskReviewLink, TradeProposal } from '../domain/proposal.js';
import type { PostgresProposalRepository } from '../infrastructure/postgres-proposal-repository.js';
import { DecisionBudgetReservation, type DecisionBudgetPolicy, type Reservation } from '../domain/decision-budget.js';
import type { PostgresBudgetRepository } from '../infrastructure/postgres-budget-repository.js';
import type { GovernanceOutboxRepository } from '../infrastructure/governance-outbox-repository.js';
import { approvalDecidedEvent, proposalCreatedEvent, riskReviewedEvent } from '../domain/governance-events.js';

@Injectable()
export class GovernanceService {
  public constructor(private readonly aggregate = new ProposalAggregate(), private readonly repository?: PostgresProposalRepository, private readonly budget = new DecisionBudgetReservation(), private readonly budgetRepository?: PostgresBudgetRepository, private readonly outbox?: GovernanceOutboxRepository) {}
  public async createDraft(command: CreateProposalCommand): Promise<TradeProposal> { const repeated = await this.repository?.findByIdempotency(command.idempotencyKey); if (repeated) return repeated; const proposal = this.aggregate.createDraft(command); await this.repository?.append(command, proposal); if (this.outbox) await this.outbox.append(proposalCreatedEvent(proposal, command.correlationId ?? command.idempotencyKey, command.createdAt), proposal.proposalId); return proposal; }
  public async getProposal(proposalId: string, version?: number): Promise<TradeProposal | undefined> { return version === undefined ? (await this.repository?.latest(proposalId)) ?? this.aggregate.get(proposalId) : this.aggregate.get(proposalId, version); }
  public async attachRiskReview(proposalId: string, proposalVersion: number, review: RiskReviewLink): Promise<TradeProposal> { const proposal = this.aggregate.attachRiskReview(proposalId, proposalVersion, review); await this.repository?.updateRiskReview(proposalId, proposalVersion, review, proposal.state); if (this.outbox) await this.outbox.append(riskReviewedEvent(proposal, review, review.evaluationId, review.reviewedAt), proposal.proposalId); return proposal; }
  public async markRiskPassed(proposalId: string, proposalVersion: number, evaluationId: string): Promise<TradeProposal> { const proposal = this.aggregate.markRiskPassed(proposalId, proposalVersion, evaluationId); if (proposal.riskReview) await this.repository?.updateRiskReview(proposalId, proposalVersion, proposal.riskReview, proposal.state); return proposal; }
  public async decide(proposalId: string, proposalVersion: number, approval: ApprovalRecord): Promise<TradeProposal> { const proposal = this.aggregate.decide(proposalId, proposalVersion, approval); await this.repository?.updateApproval(proposalId, proposalVersion, approval, proposal.state); if (this.outbox) await this.outbox.append(approvalDecidedEvent(proposal, approval, approval.actorId, approval.decidedAt), proposal.proposalId); return proposal; }
  public async reserveBudget(input: { reservationId: string; portfolioId: string; tradingDate: string; reason: string; proposalId: string; kind: 'HOLD' | 'REBALANCE'; idempotencyKey: string }, policy: DecisionBudgetPolicy): Promise<Reservation> { const repeated = await this.budgetRepository?.findByIdempotency(input.idempotencyKey); if (repeated) return repeated; const reservation = this.budget.reserve(input, policy); if (reservation.status === 'RESERVED') await this.budgetRepository?.append(reservation, input.idempotencyKey); return reservation; }
  public async releaseBudget(reservationId: string): Promise<Reservation> { const reservation = this.budget.release(reservationId); await this.budgetRepository?.release(reservationId); return reservation; }
}
