import { BadRequestException, ServiceUnavailableException, UseGuards, Body, Controller, Get, Injectable, Module, Optional, Param, Post } from '@nestjs/common'; import { NestFactory } from '@nestjs/core'; import { FastifyAdapter } from '@nestjs/platform-fastify'; import { readServiceConfig } from '@stock/config'; import { log } from '@stock/observability'; import { Pool } from 'pg'; import { readFile } from 'node:fs/promises'; import { connect, type NatsConnection } from 'nats'; import { readAutoExecutionConfig } from '../application/auto-execution-config.js'; import { ExecutionService } from '../application/execution-service.js'; import type { ApprovedExecutionCommand, OrderIntentStatus } from '../domain/execution.js'; import { ExecutionAuthorizationUnavailable, denyExecution, GrantExecutionAuthorization, HttpExecutionAuthorizationGrantReader } from '../application/execution-authorization.js';
import { ExecutionWriteGuard } from '../application/execution-write-guard.js';
import { ExecutionOutboxRepository } from '../infrastructure/execution-outbox-repository.js'; import { ExecutionOutboxWorker } from '../application/outbox-worker.js'; import { ExecutionNatsPublisher, ExecutionOutboxScheduler } from '../application/outbox-runtime.js';
const serviceName = 'trade-execution-service';
const databasePool = process.env.TRADE_EXECUTION_DATABASE_URL ? new Pool({ connectionString: process.env.TRADE_EXECUTION_DATABASE_URL, max: 5 }) : undefined;
let natsConnection: NatsConnection | undefined; let outboxScheduler: ExecutionOutboxScheduler | undefined;
const authorization = process.env.GOVERNANCE_AUTHORIZATION_BASE_URL && process.env.GOVERNANCE_INTERNAL_TOKEN ? new GrantExecutionAuthorization(new HttpExecutionAuthorizationGrantReader(process.env.GOVERNANCE_AUTHORIZATION_BASE_URL, process.env.GOVERNANCE_INTERNAL_TOKEN)) : denyExecution;
@Controller() class HealthController { @Get('/live') live() { return { status: 'UP' }; } @Get('/ready') ready() { return { status: 'UP', dependencies: {} }; } @Get('/metrics') metrics() { return ''; } @Get('/version') version() { return { service: serviceName, version: '0.1.0' }; } }
@UseGuards(ExecutionWriteGuard)
@Controller('/api/v1/execution') export class ExecutionController { public constructor(@Optional() private readonly service: ExecutionService = executionService) {} @Post('batches') async createBatch(@Body() body: ApprovedExecutionCommand) { try { return await this.service.createBatch(body); } catch (error) { if (error instanceof ExecutionAuthorizationUnavailable) throw new ServiceUnavailableException(error.message); throw new BadRequestException(error instanceof Error ? error.message : 'invalid execution command'); } } @Post('batches/:batchId/intents/:intentId/status') async transition(@Param('batchId') batchId: string, @Param('intentId') intentId: string, @Body() body: { status: OrderIntentStatus }) { try { return await this.service.transitionIntent(batchId, intentId, body.status); } catch (error) { throw new BadRequestException(error instanceof Error ? error.message : 'invalid intent transition'); } } @Post('batches/:batchId/fills') async fill(@Param('batchId') batchId: string, @Body() body: { fillId: string; intentId: string; filledQuantity: string; fillPrice: string; occurredAt: string; idempotencyKey: string }) { try { return await this.service.recordFill(batchId, body); } catch (error) { throw new BadRequestException(error instanceof Error ? error.message : 'invalid fill'); } } @Post('reconciliation') async openReconciliation(@Body() body: { caseId: string; rebalanceBatchId: string; intentId: string; expectedQuantity: string; actualQuantity: string; updatedAt: string; idempotencyKey: string }) { try { return await this.service.openReconciliation(body); } catch (error) { throw new BadRequestException(error instanceof Error ? error.message : 'invalid reconciliation case'); } } @Post('reconciliation/:caseId/resolve') async resolveReconciliation(@Param('caseId') caseId: string, @Body() body: { status: 'RESOLVED' | 'IGNORED'; reason: string; updatedAt: string }) { try { return await this.service.resolveReconciliation(caseId, body.status, body.reason, body.updatedAt); } catch (error) { throw new BadRequestException(error instanceof Error ? error.message : 'invalid reconciliation resolution'); } } }
const executionService = databasePool ? new ExecutionService(undefined, undefined, undefined, undefined, authorization, databasePool) : new ExecutionService(undefined, undefined, undefined, undefined, authorization);
@Injectable() class DatabaseLifecycle { async onApplicationShutdown(): Promise<void> { outboxScheduler?.stop(); if (process.env.NODE_ENV !== 'test' && natsConnection) await natsConnection.drain(); if (process.env.NODE_ENV !== 'test' && databasePool) await databasePool.end(); } }
@Module({ controllers: [HealthController, ExecutionController], providers: [ExecutionWriteGuard, { provide: ExecutionService, useFactory: () => executionService }, DatabaseLifecycle] }) class AppModule {}
async function bootstrap() { const config = readServiceConfig({ ...process.env, SERVICE_NAME: serviceName }); const autoExecution = readAutoExecutionConfig(process.env); if (databasePool) await databasePool.query(await readFile(new URL('../../migrations/001_execution.sql', import.meta.url), 'utf8')); if (databasePool && process.env.NATS_URL) { natsConnection = await connect({ servers: process.env.NATS_URL }); const manager = await natsConnection.jetstreamManager(); try { await manager.streams.add({ name: 'STOCK_EXECUTION', subjects: ['stock.trade-execution.>'] }); } catch { /* 已存在时复用 */ } outboxScheduler = new ExecutionOutboxScheduler(new ExecutionOutboxWorker(new ExecutionOutboxRepository(databasePool), new ExecutionNatsPublisher(natsConnection))); outboxScheduler.start(); } const app = await NestFactory.create(AppModule, new FastifyAdapter()); app.enableShutdownHooks(); await app.listen(config.PORT, '0.0.0.0'); log('service.started', { service: serviceName, autoExecutionEnabled: autoExecution.policy.enabled, outboxPublisherEnabled: Boolean(outboxScheduler) }); } if (process.env.NODE_ENV !== 'test') void bootstrap();
