import type { Reservation } from '../domain/decision-budget.js';
import type { SqlClient } from './postgres-proposal-repository.js';

export class PostgresBudgetRepository {
  public constructor(private readonly client: SqlClient) {}
  public async findByIdempotency(key: string): Promise<Reservation | undefined> { const result = await this.client.query<{ reservation_id: string; portfolio_id: string; trading_date: string; proposal_id: string; reason: string; batch_number: number; status: Reservation['status'] }>('SELECT reservation_id, portfolio_id, trading_date, proposal_id, reason, batch_number, status FROM decision_budget_reservations WHERE idempotency_key = $1', [key]); const row = result.rows[0]; return row && { reservationId: row.reservation_id, portfolioId: row.portfolio_id, tradingDate: row.trading_date, proposalId: row.proposal_id, reason: row.reason, batchNumber: row.batch_number, status: row.status }; }
  public async find(reservationId: string): Promise<Reservation | undefined> { const result = await this.client.query<{ reservation_id: string; portfolio_id: string; trading_date: string; proposal_id: string; reason: string; batch_number: number; status: Reservation['status'] }>('SELECT reservation_id, portfolio_id, trading_date, proposal_id, reason, batch_number, status FROM decision_budget_reservations WHERE reservation_id = $1', [reservationId]); const row = result.rows[0]; return row && { reservationId: row.reservation_id, portfolioId: row.portfolio_id, tradingDate: row.trading_date, proposalId: row.proposal_id, reason: row.reason, batchNumber: row.batch_number, status: row.status }; }
  public async countActive(portfolioId: string, tradingDate: string): Promise<number> { const result = await this.client.query<{ count: string }>("SELECT count(*)::text AS count FROM decision_budget_reservations WHERE portfolio_id = $1 AND trading_date = $2 AND status <> 'RELEASED' AND batch_number > 0", [portfolioId, tradingDate]); return Number(result.rows[0]?.count ?? 0); }
  public async append(reservation: Reservation, idempotencyKey: string): Promise<void> { await this.client.query('INSERT INTO decision_budget_reservations (reservation_id, portfolio_id, trading_date, proposal_id, reason, batch_number, status, idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)', [reservation.reservationId, reservation.portfolioId, reservation.tradingDate, reservation.proposalId, reservation.reason, reservation.batchNumber, reservation.status, idempotencyKey]); }
  public async markDispatching(reservationId: string): Promise<void> { await this.client.query("UPDATE decision_budget_reservations SET status = 'DISPATCHING' WHERE reservation_id = $1 AND status = 'RESERVED'", [reservationId]); }
  public async consume(reservationId: string): Promise<void> { await this.client.query("UPDATE decision_budget_reservations SET status = 'CONSUMED' WHERE reservation_id = $1 AND status = 'DISPATCHING'", [reservationId]); }
  public async release(reservationId: string): Promise<void> { await this.client.query("UPDATE decision_budget_reservations SET status = 'RELEASED' WHERE reservation_id = $1 AND status IN ('RESERVED', 'DISPATCHING')", [reservationId]); }
}
